title: new-emotion-reader
description: >-
  This is a course that teaches you how to build an emotion-reader using Azure
  Functions.
template:
  repo: new-emotion-reader-template
  name: new-emotion-reader
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
